FROM node:20-alpine AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app

ARG APP_ENV=staging
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG GOOGLE_CLOUD_PROJECT
ARG FIREBASE_PROJECT_ID
ARG SPORTS_PROVIDER=mock
ARG SIM_DEFAULT_RUNS=10000
ARG PUBLIC_SIM_RUNS=100000
ARG LIVE_CACHE_TTL_SEC=15
ARG INSIGHT_CACHE_TTL_SEC=3600
ARG PUBLIC_SIM_CACHE_TTL_SEC=86400
ARG AD_PROVIDER=adsense
ARG CONSENT_MODE=strict

ENV APP_ENV=$APP_ENV
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV SPORTS_PROVIDER=$SPORTS_PROVIDER
ENV SIM_DEFAULT_RUNS=$SIM_DEFAULT_RUNS
ENV PUBLIC_SIM_RUNS=$PUBLIC_SIM_RUNS
ENV LIVE_CACHE_TTL_SEC=$LIVE_CACHE_TTL_SEC
ENV INSIGHT_CACHE_TTL_SEC=$INSIGHT_CACHE_TTL_SEC
ENV PUBLIC_SIM_CACHE_TTL_SEC=$PUBLIC_SIM_CACHE_TTL_SEC
ENV AD_PROVIDER=$AD_PROVIDER
ENV CONSENT_MODE=$CONSENT_MODE

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8080
ENV HOSTNAME=0.0.0.0

COPY --from=builder --chown=node:node /app/package.json ./package.json
COPY --from=builder --chown=node:node /app/package-lock.json ./package-lock.json
COPY --from=builder --chown=node:node /app/public ./public
COPY --from=builder --chown=node:node /app/.next/static ./.next/static
COPY --from=builder --chown=node:node /app/.next/standalone ./

USER node

EXPOSE 8080

CMD ["node", "server.js"]
